# Generated by Django 3.2 on 2021-08-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default='', max_length=1000000),
            preserve_default=False,
        ),
    ]
